runtime: php55
api_version: 1

handlers:
- url: /
  script: index.php

- url: /(.+\.(gif|png|jpg|css|ttf))
  static_files: \1
  upload: .+\.(gif|png|jpg|css|ttf)$
  application_readable: true

- url: /(.+\.php)
  script: \1